### ISSUE TITLE
react-native-safe-area-context dependency "warning"

### ISSUE THREAD

**Issue by dkastl** [consento-org/mobile#101]
When starting  the app locally with Expo the following warning (?) shows up

> Some of your project's dependencies are not compatible with currently installed expo package version:
>  - react-native-safe-area-context - expected version range: 3.1.4 - actual version installed: ^3.1.8
> Your project may not work correctly until you install the correct versions of the packages.
> To install the correct versions of these packages, please run: expo install [package-name ...]

But it seems the currenrtly installed version already exceeds the expected one.

**Comment by martinheidegger** [comment]
Fixed in update branch.
