### ISSUE TITLE
After locking a vault it changes immediately to status "pending" again

### ISSUE THREAD

**Issue by dkastl** [consento-org/mobile#102]
**Describe the bug**
When locking a vault by clicking the "lock" button, the screen changes to the list auf vaults, and the status of the previously locked vault changes to status "Pending". At the same time the lockee receives an unlock request, which opens the vault again.
When trying to lock again it continues like this forever.

**To Reproduce**
- add a lockee (don't set a name)
- create a vault
- add a photo
- add a lockee
- lock the vault

**Expected behavior**
Do not make an unlock request right after locking a vault.

**Platform/smartphone (please complete the following information):**
 - Device: Android phones (Umidigi, Xoami Redmi)
 - OS: Android 10 
 - App Version https://github.com/consento-org/mobile/pull/93

**Additional context**
When access is denied (and not approved) the lock status continues to wait for consent.

**Comment by martinheidegger** [comment]
Thank you, should be fixed with last commit in updates branch.
