### ISSUE TITLE
Add contributor guide

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/mobile#14]
@Tannybunny, @marcchataigner  and I already worked on a contributor guide. ↓

https://pad.dyne.org/code/#/2/code/edit/ZaGeNqfGUWjWMaUk2Z3gZoO0/

Lets add that to this repository.

**Comment by marcchataigner-zz** [comment]
- [ ] some text requires an expert (for instance why enable Force Push)
- [x] I prepared the PNG that I will upload tomorrow
- [x] I need to go through again the 'how to make a nice contributing.md page'.
