### ISSUE TITLE
Alert symbol for unseen, active Consento

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/mobile#20]
It might be good to change the Consentos Icon to have an alert symbol if there is a consento that the user hasn't seen before.

cc. @consento-org/design

**Comment by Tannybunny** [comment]
<img width="1000" alt="Screen Shot 2020-01-24 at 16 40 06" src="https://user-images.githubusercontent.com/51223963/73052317-3ca44000-3ec8-11ea-8f35-75f00a9f0380.png">

like this?

**Comment by martinheidegger** [comment]
Yes, however I don't know how to render a number into it at the moment.

**Comment by Tannybunny** [comment]
Ok then how about this for the moment:
<img width="700" alt="Screen Shot 2020-01-24 at 17 12 47" src="https://user-images.githubusercontent.com/51223963/73054070-cbb35700-3ecc-11ea-9a47-e0ede288b571.png">

**Comment by martinheidegger** [comment]
That should be easily add-able and I should be able to turn it into a "number" display at a later point.
