### ISSUE TITLE
Create Application on Google Play

### ISSUE THREAD

**Issue by dkastl** [consento-org/mobile#30]
To build and maintain an application on Google Play with Expo, the application needs to be created first via Google Play Console. The following required informations is necessary:

- [x] Title (max 50 characters)
- [x] Short description (max 80 characters)
- [x] Full description (max 4000 characters, check also https://play.google.com/about/storelisting-promotional/metadata/)

Also check: https://play.google.com/about/developer-content-policy/

**Required graphics materials**

https://developer.android.com/google-play/resources/icon-design-specifications

- [x] Hi-res icon - 512 x 512, 32-bit PNG, transparency not allowed anymore
- [x] Screenshots - JPEG or 24-bit PNG (no alpha). Min length for any side: 320px. Max length for any side: 3840px. At least 2 screenshots are required overall. Max 8 screenshots per type. (PHONE, TABLET, ANDROID TV, WEAR OS)
- [x] Feature Graphic - 1024 w x 500 h, JPG or 24-bit PNG (no alpha)

**Categorization**

- [x] Application type (selectbox)
- [x] Category (selectbox)
- [x] Tags https://support.google.com/googleplay/android-developer/answer/113475

**Comment by dkastl** [comment]
@marcchataigner or @Tannybunny , could you help me with the graphics materials?

**Comment by marcchataigner-zz** [comment]
@dkastl 

consento

An app to handle your confidential data through people you trust.

```
Our mission is to make our digital society a place where we all can handle our digital lives the same way as we learned to do in real life.

We believe encrypted data management can be redesigned with human trust at its core.

With this first version of consento, you will be able to encrypt images and text files on your mobile phone. 

Your data always remains your data. Data is encrypted on your device only, and the encryption key is split into unique parts that you can distribute to the device of people you trust. 

To share the unique split key, consento enables you to pair your device with the device of people you trust. Consento create device to device communication. 

To access the data, consento creates a unique "human-factor authentication". 

Read more about how consento works on https://www.consento.org/.

In the coming next versions, individuals will be able to encrypt uploaded files, like passwords, wallet keys, official documents, … Professionals and organizations will be able to manage their customer data, patient records, employee data, contracts, and router confidential documents. 

Future versions will soon enable you to encrypt folders, both on your mobile devices and your desktop machines.

Consento is smarter than a password manager. Password managers are great, but have a major flaw: you lose the master key and you lose everything. With consento the master key is split into unique parts and you can distribute them to people you trust. No one will be able to access the encrypted data without their consent. 

In the future version, consento will enable you to store large datasets. Up-to you to devices to connect together. 
```

**Comment by marcchataigner-zz** [comment]
512x512 icon & screenshots: 
https://drive.google.com/open?id=1o2yiwzvU-vhpjBYip3IOnARJ_X5IX_8S&authuser=marc@georepublic.de&usp=drive_fs

**Comment by marcchataigner-zz** [comment]
@dkastl the 'feature graphic', what could it be?

**Comment by dkastl** [comment]
Are the PNG's for the app icon non-transparent?
iOS seems to require this as well and the currently used icon graphics is rejected when trying to build an iOS app with Expo.

**Comment by dkastl** [comment]
This is all the information the registration page gives me. So I'm not sure what "Feature Graphic" is either.

![Screenshot from 2020-01-27 21-09-46](https://user-images.githubusercontent.com/227762/73173738-69b35580-4149-11ea-9c8a-474daa68a14b.png)

**Comment by dkastl** [comment]
Maybe something like a responsive banner/background image?

**Comment by dkastl** [comment]
https://support.google.com/googleplay/android-developer/answer/1078870

**Comment by dkastl** [comment]
The screenshots are getting refused

![Screenshot from 2020-01-27 21-19-01](https://user-images.githubusercontent.com/227762/73174297-bd726e80-414a-11ea-8bf3-25ed650c434e.png)

> You need to resize your screenshot. Min length for any side: 320px. Max length for any side: 3840px. Max aspect ratio: 2:1.

Aspect ration is almost OK ...

**Comment by dkastl** [comment]
Just shrinked the height of the screenshots for now.

**Comment by marcchataigner-zz** [comment]
> Are the PNG's for the app icon non-transparent?
> iOS seems to require this as well and the currently used icon graphics is rejected when trying to build an iOS app with Expo.

@dkastl In the same [folder](https://drive.google.com/open?id=1o2yiwzvU-vhpjBYip3IOnARJ_X5IX_8S&authuser=marc@georepublic.de&usp=drive_fs), you have a `512x512-on-white.png` file which is full white background. The previous one had rounded corners.

**Comment by marcchataigner-zz** [comment]
It's funny because the screenshots are actually real 'screenshots'   :-)    made on Android on top of that   :-)

**Comment by Tannybunny** [comment]
Would it be ok to prepare graphics like here https://play.google.com/store/apps/details?id=jp.naver.line.android or here https://play.google.com/store/apps/details?id=jp.ne.paypay.android.app (for example) instead of just a pure screenshot? I mean add a short headline that says something about the app .. usually companies post not only screenshots there but a bit more designed graphics that show a screen or part of it + some additonal text or graphic .. I can prepare those :)
