### ISSUE TITLE
Consento applications works

### ISSUE THREAD

**Issue by Trapist** [consento-org/mobile#40]
Hi Consento,

Your application is impressive and it works! I am very pleased with what I've seen. 

BTW on p.9 of the overview.pdf it says:"If you like this system but need special features, please don't send us an issue: https://github.com/consento-org/mobile/issues/new"

I believe that is a typo, right?

Thank you for this amazing app,
Elena

P.S. I am using gitHub...

**Comment by martinheidegger** [comment]
This is indeed a typo, though telling people not to do something is the safest way for them to actually do it.

I submitted #41 to fix this issue.
