### ISSUE TITLE
Empty Vault screen

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/mobile#5]
When you start the app, it contains three vaults but all three can be deleted which leaves you with an ugly empty screen. Maybe we can have a small illustration on what to do in that case?

**Comment by marcchataigner-zz** [comment]
@martinheidegger I pushed a screen for when there is no vaults. (but now that I see the git, I think maybe Tanja already did that)

**Comment by marcchataigner-zz** [comment]
![Screen Shot 2020-01-22 at 10 30 34](https://user-images.githubusercontent.com/3974900/72857869-3d8b7500-3d02-11ea-9059-dce3dfd9ac0a.png)

**Comment by martinheidegger** [comment]
Your commit is 8873b62 the current master commit is 724a263f
If you compare them with the github UI ↓ then you can see that you added the screen. :+1:

https://github.com/consento-org/mobile/compare/724a263f..8873b62

**Comment by marcchataigner-zz** [comment]
Wow, I added a screen.   :-)   🍾   Thx

**Comment by martinheidegger** [comment]
You can create a pull request: https://github.com/consento-org/mobile/compare/master...marc

<img width="224" alt="Screen Shot 2020-01-22 at 11 18 05" src="https://user-images.githubusercontent.com/914122/72860000-e76e0000-3d08-11ea-88e1-35ca3cb1f97d.png">


_(Note: you can use more than one branch for your work, this makes pull requests easier)_
