### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by dkastl** [consento-org/mobile#50]
Report from App Store Connect:

> Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by martinheidegger** [comment]
> This should be resolved via [#6593](https://github.com/expo/expo/pull/6593) and will be released with [SDK 37](https://github.com/orgs/expo/projects/5)

**Comment by dkastl** [comment]
OK, good to know. I just copied this from the app review email.

**Comment by martinheidegger** [comment]
Likely fixed by #93 closing for now, please reopen if it still occurs.
