### ISSUE TITLE
iOS - not possible to name a relation

### ISSUE THREAD

**Issue by marcchataigner-zz** [consento-org/mobile#54]
On iOS (via Test Flight) when adding a relation, it is not possible to name the relation. 

The text field does not take entry and the keyboard does not show up. 

(and when taping the avatar icon couple of times to refresh it, the app tends to crash)

![IMG_B81C64F967D5-1](https://user-images.githubusercontent.com/3974900/73812121-0dbe9000-481f-11ea-901c-62247f4c8d1b.jpeg)

**Comment by martinheidegger** [comment]
@dkastl is there an error log in testflight when the app crashes?

**Comment by dkastl** [comment]
Yes, I was looking at Testflight and this is what I can download. Not sure it's helpful.
[testflight_feedback.zip](https://github.com/consento-org/mobile/files/4163317/testflight_feedback.zip)

**Comment by dkastl** [comment]
Not sure if Testflight provides tools for users to send bug reports and useful information. This report was sent by @halsk and I remember he did something on the phone to file this report. I just don't know what.
