### ISSUE TITLE
Vault loading screen

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/mobile#6]
The vaults get loaded from the device. There is already a VaultCard design that shows when the vault is loading but we don't have yet a design for the vault screen when it is loaded. Would be good to have.

**Comment by Tannybunny** [comment]
How about a simple gif like this (+ text)
I'm not sure though gifs can be integrated into sketch, maybe we have to put it into the asserts folder manually?
![consento_symbol_animation](https://user-images.githubusercontent.com/51223963/73053146-534b9680-3eca-11ea-8759-9e5097d87e03.gif)

**Comment by martinheidegger** [comment]
Hmm, there is support for animated gifs in react-native but there is support missing in sketch. But you can add the animated gif in the assets folder and add a placeholder of the matching size in `design.sketch` file

**Comment by martinheidegger** [comment]
The gif should also be in various resolutions.
