### ISSUE TITLE
Screenshots of App Store Connect

### ISSUE THREAD

**Issue by dkastl** [consento-org/mobile#79]
**Is your feature request related to a problem? Please describe.**

To be able to submit the app to the iOS app store we need to provide screenshots.

**Describe the solution you'd like**

Screenshot requirements are described in https://help.apple.com/app-store-connect/#/devd274dd925

Probably we need the following:
- [x] 6.5 inch - 1242 x 2688 pixels (portrait)
- [x] 5.5 inch - 1242 x 2208 pixels (portrait)
- [x] 12.9 inch - 2048 x 2732 pixels (portrait)

I don't know where to turn off iPad support. The last option would not be necessary if iPad is not supported.

**Describe alternatives you've considered**

It's not necessary to submit the app for review, but it could provide some useful feedback. It would also help to prepare for a public release

**Comment by martinheidegger** [comment]
![Simulator Screen Shot - iPhone SE - 2020-02-15 at 10 44 55](https://user-images.githubusercontent.com/914122/74579749-64c32280-4fe0-11ea-831f-d3a62091e65a.png)
![Simulator Screen Shot - iPhone SE - 2020-02-15 at 10 44 43](https://user-images.githubusercontent.com/914122/74579750-6856a980-4fe0-11ea-8b9d-047204a08572.png)
![Simulator Screen Shot - iPhone 8 - 2020-02-15 at 10 40 09](https://user-images.githubusercontent.com/914122/74579751-68ef4000-4fe0-11ea-8a58-362366a69a3f.png)
![Simulator Screen Shot - iPhone 8 - 2020-02-15 at 10 39 56](https://user-images.githubusercontent.com/914122/74579753-6987d680-4fe0-11ea-9842-40648c85ba36.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-02-15 at 10 29 51](https://user-images.githubusercontent.com/914122/74579755-6a206d00-4fe0-11ea-8572-dec997fa1b20.png)
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-02-15 at 10 29 40](https://user-images.githubusercontent.com/914122/74579756-6ab90380-4fe0-11ea-8c61-4fe12a719820.png)
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-02-15 at 10 17 40](https://user-images.githubusercontent.com/914122/74579757-6ab90380-4fe0-11ea-9276-434b077424fe.png)
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-02-15 at 10 17 25](https://user-images.githubusercontent.com/914122/74579758-6b519a00-4fe0-11ea-849e-bc86552634d0.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-15 at 10 11 00](https://user-images.githubusercontent.com/914122/74579759-6bea3080-4fe0-11ea-93ec-d64a9dc8a899.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-15 at 10 08 42](https://user-images.githubusercontent.com/914122/74579761-6c82c700-4fe0-11ea-8c38-e2b7ba3b2e92.png)

**Comment by martinheidegger** [comment]
@dkastl Are ↑ sufficient?

**Comment by dkastl** [comment]
Tried to submit, so let's see if it's sufficient.

**Comment by dkastl** [comment]
No complaint so far.
