### ISSUE TITLE
Text on Relations screen is cut off

### ISSUE THREAD

**Issue by chmac** [consento-org/mobile#92]
**Screenshots**

![image](https://user-images.githubusercontent.com/690997/91710903-493af600-eb85-11ea-86c6-04c7424542d5.png)

**Smartphone (please complete the following information):**
 - Device: Moto X4

**Comment by martinheidegger** [comment]
Thanks @chmac for letting us know!

This is an issue with `EmptyView`. It doesn't wrapped in a [`<ScrollView>`](https://reactnative.dev/docs/scrollview.html). I am busy with #93 and with a presentation for `expo-export` that explains the capability/limitations of the system.

https://github.com/consento-org/mobile/blob/b16b94538038bb3451916ad87e0850f748f87af9/src/screens/components/EmptyView.tsx#L26-L37

I would welcome a Pull Request to fix this issue.

**Comment by martinheidegger** [comment]
Fixed in #93
